/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.guilhermedelemos;

import io.github.guilhermedelemos.blackjack.Blackjack;

public class App {

    public static void main(String[] args) {
        Blackjack game = new Blackjack();
        game.execute();
    }

}
