/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.guilhermedelemos;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    /*
     * Será que este teste é útil?
     */
    @Test void appInstance() {
        App app = new App();
        assertNotNull(app);
    }

}
